#!/bin/bash
set -e

# =============================================================================
# RESET TEMPLATE - For template maintainers only
# =============================================================================
#
# This script resets the repository to its clean template state after testing
# the setup.sh script. It removes all generated files and restores modified
# files to their original state.
#
# USE CASE: You're maintaining this starter template and want to test setup.sh
# without committing the generated artifacts.
#
# WARNING: This will discard ALL uncommitted changes. Make sure you've committed
# any template improvements before running this script.
#
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${YELLOW}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${YELLOW}║         RESET TEMPLATE TO CLEAN STATE                      ║${NC}"
echo -e "${YELLOW}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${RED}⚠️  WARNING: This will:${NC}"
echo "  • Remove ALL generated files (drizzle/, .wrangler/, .dev.vars, etc.)"
echo "  • Restore ALL modified files to their git state"
echo "  • Remove node_modules and pnpm-lock.yaml"
echo ""
echo -e "${YELLOW}This is intended for template maintainers testing setup.sh${NC}"
echo ""

read -p "Are you sure you want to reset? (y/N) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Reset cancelled."
    exit 0
fi

echo ""
echo -e "${BLUE}Starting reset...${NC}"
echo ""

# =============================================================================
# REMOVE GENERATED FILES
# =============================================================================

echo -e "${YELLOW}Removing generated files...${NC}"

# Database migrations (generated by pnpm db:generate)
if [ -d "drizzle" ]; then
    rm -rf drizzle
    echo "  ✓ Removed drizzle/"
fi

# Wrangler local state (local D1 database, etc.)
if [ -d ".wrangler" ]; then
    rm -rf .wrangler
    echo "  ✓ Removed .wrangler/"
fi

# Environment files
if [ -f ".dev.vars" ]; then
    rm -f .dev.vars
    echo "  ✓ Removed .dev.vars"
fi

if [ -f ".env.local" ]; then
    rm -f .env.local
    echo "  ✓ Removed .env.local"
fi

# GitHub secrets helper
if [ -f ".github-secrets-setup.txt" ]; then
    rm -f .github-secrets-setup.txt
    echo "  ✓ Removed .github-secrets-setup.txt"
fi

# Backup files created by setup.sh
rm -f wrangler.jsonc.backup
rm -f package.json.backup
rm -f next.config.ts.backup
rm -f scripts/db-studio.sh.backup
rm -f .github/workflows/deploy.yml.backup
echo "  ✓ Removed backup files (*.backup)"

# Generated favicons (if they exist and aren't the originals)
# We check if they were recently modified (within last hour) to avoid removing template files
FAVICON_FILES=(
    "public/favicon-16x16.png"
    "public/favicon-32x32.png"
    "public/android-chrome-192x192.png"
    "public/android-chrome-512x512.png"
    "public/apple-touch-icon.png"
    "public/favicon.ico"
)

for file in "${FAVICON_FILES[@]}"; do
    if [ -f "$file" ]; then
        # Check if file is tracked by git
        if ! git ls-files --error-unmatch "$file" &>/dev/null; then
            rm -f "$file"
            echo "  ✓ Removed $file (untracked)"
        fi
    fi
done

# =============================================================================
# RESTORE MODIFIED FILES
# =============================================================================

echo ""
echo -e "${YELLOW}Restoring modified files to git state...${NC}"

# List of files that setup.sh modifies
MODIFIED_FILES=(
    "next.config.ts"
    "wrangler.jsonc"
    "package.json"
    "scripts/db-studio.sh"
    ".github/workflows/deploy.yml"
    "src/app/(legal)/privacy/page.mdx"
    "src/app/(legal)/terms/page.mdx"
    "public/site.webmanifest"
    "cloudflare-env.d.ts"
)

for file in "${MODIFIED_FILES[@]}"; do
    if [ -f "$file" ]; then
        git checkout -- "$file" 2>/dev/null && echo "  ✓ Restored $file" || echo "  - $file (no changes)"
    fi
done

# =============================================================================
# CLEAN NODE MODULES (optional but recommended for clean state)
# =============================================================================

echo ""
read -p "Remove node_modules and pnpm-lock.yaml? (recommended for clean state) (y/N) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ -d "node_modules" ]; then
        rm -rf node_modules
        echo "  ✓ Removed node_modules/"
    fi

    if [ -f "pnpm-lock.yaml" ]; then
        # Only remove if it's not tracked by git
        if ! git ls-files --error-unmatch "pnpm-lock.yaml" &>/dev/null; then
            rm -f pnpm-lock.yaml
            echo "  ✓ Removed pnpm-lock.yaml"
        else
            echo "  - pnpm-lock.yaml is tracked by git, keeping it"
        fi
    fi

    echo ""
    echo -e "${BLUE}Run 'pnpm install' to reinstall dependencies${NC}"
fi

# =============================================================================
# SUMMARY
# =============================================================================

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         RESET COMPLETE                                     ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "The repository is now in a clean template state."
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run 'pnpm install' if you removed node_modules"
echo "  2. Run 'bash scripts/setup.sh' to test the setup again"
echo ""
echo -e "${BLUE}Tip: Add test artifacts to .git/info/exclude to ignore them locally${NC}"
echo "     See TEMPLATE_DEVELOPMENT.md for details"
echo ""
